# Generated by Django 2.2.4 on 2020-03-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='facility',
            field=models.CharField(default='restaurants', max_length=30),
        ),
    ]
